INSERT INTO PolyOmniaDb.dbo.Videos (Title,UrlOrPath,SourceType,CreatedAt,Description,GenreId,UserId,AllowDownload,IsPublished,IsApproved,Duration,ThumbnailUrlOrPath,ViewCount) VALUES
	 (N'Уроки JavaScript з нуля / #1 – Основи мови JS для початківців. Що до чого?',N'https://www.youtube.com/embed/RS4LF577fj4',2,'2026-10-10 21:27:20.4604875',N'Курс з вивчення мови програмування JavaScript з нуля для початківців. За курс ми з вами познайомимося з написанням функцій на JS, а також з маніпуляцією HTML об''єктів за рахунок ДжаваCкрипт. У першому уроці ми поговоримо про JS, дізнаємося, що він робить і на що він здатний.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/RS4LF577fj4/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #2 – Головні концепції при роботі з JS',N'https://www.youtube.com/embed/M518DSk9Xa8',2,'2026-10-10 21:28:11.5410448',N'Перш ніж розпочати розробку програм на JavaScript необхідно вивчити деякі основні моменти. Під час уроку ми познайомимося зі спеціальними тегами «noscript» та «script», а також на практиці розглянемо приклад застосування мови JS.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/M518DSk9Xa8/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #3 – Виведення інформації. Робота з консоллю',N'https://www.youtube.com/embed/rQHjepiSy0k',2,'2026-10-10 21:28:45.0614186',N'Виведення інформації – важлива частина у будь-якій мові програмування. Ми навчимося виводити інформацію в консоль, а також прямо на сторінку веб-сайту. Додатково за урок ми ознайомимося з консоллю розробника.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/rQHjepiSy0k/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #4 – Змінні та типи даних у JS',N'https://www.youtube.com/embed/o1nyyEThAtw',2,'2026-10-10 21:29:23.6832992',N'Змінні та типи даних – основа будь-якої мови програмування. За урок ми навчимося створювати та працювати зі змінними у мові програмування JavaScript. Додатково ми поговоримо про типи даних у JS.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/o1nyyEThAtw/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #5 – Математичні дії. Клас Math у JavaScript',N'https://www.youtube.com/embed/1TF1IfhUDuA',2,'2026-10-10 21:29:56.7543721',N'У мові JavaScript є спеціальні конструкції виконання математичних дій. За урок ми навчимося обробляти стандартні математичні операції, а також познайомимося з окремим класом Math.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/1TF1IfhUDuA/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #6 – Умовні оператори у мові JavaScript',N'https://www.youtube.com/embed/PJF2cB4kLso',2,'2026-10-10 21:30:31.2842268',N'Умовні конструкції дозволяють перевірити якийсь вираз і в залежності від його результату виконати необхідний код. В уроці ми познайомимося з конструкцією «if – else» та конструкцією «switch – case».',1,1,0,1,1,N'',N'https://img.youtube.com/vi/PJF2cB4kLso/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #7 – Масиви даних. Одновимірні та багатовимірні масиви',N'https://www.youtube.com/embed/KPACLYD1jTY',2,'2026-10-10 21:31:08.8446687',N'За урок ми навчимося працювати з масивами даних у мові JavaScript. За допомогою масивів можна зберігати великі обсяги інформації в одному місці. Ми вивчимо одновимірні та багатовимірні масиви даних.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/KPACLYD1jTY/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #8 – Цикли у JavaScript. Оператори циклів',N'https://www.youtube.com/embed/jMQAkhwYb5U',2,'2026-10-10 21:31:48.1608213',N'За рахунок циклів ви можете створювати код, який буде циклічно виконаний певну кількість разів. Ми в уроці розглянемо створення циклів у JavaScript. Ми вивчимо цикли: for, while та do while. Додатково ми будемо вивчати оператори для циклів.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/jMQAkhwYb5U/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #9 – Функціональні вікна (alert, prompt, confirm)',N'https://www.youtube.com/embed/UIaYzWJl5X0',2,'2026-10-10 21:32:17.7146265',N'У мові JavaScript є кілька вбудованих функцій, що забезпечують створення вспливаючих вікон. За урок ми розглянемо три функції, що надають можливість реалізації вікон з різним набором дій. Ми вивчимо методи: alert, confirm та prompt.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/UIaYzWJl5X0/hqdefault.jpg',0),
	 (N'Уроки JavaScript з нуля / #10 – Функції у мові JavaScript',N'https://www.youtube.com/embed/847iSyAkEFk',2,'2026-10-10 21:32:47.5504926',N'Функції JavaScript виконують важливу роль. Вони забезпечують скорочення коду за допомогою винесення його у окремі місця. За урок ми навчимося створювати функції та передавати в них значення.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/847iSyAkEFk/hqdefault.jpg',0);
INSERT INTO PolyOmniaDb.dbo.Videos (Title,UrlOrPath,SourceType,CreatedAt,Description,GenreId,UserId,AllowDownload,IsPublished,IsApproved,Duration,ThumbnailUrlOrPath,ViewCount) VALUES
	 (N'Уроки JavaScript з нуля / #11 – Події та обробник подій у JavaScript',N'https://www.youtube.com/embed/skMtNVd3h-Y',2,'2026-10-10 21:33:30.4311260',N'Для роботи з користувачем вам необхідно навчитися обробляти його дії: натискання, переміщення, наведення миші та інше. За урок ми навчимося відстежувати дії користувача та залежно від них виконувати різний код.',1,1,0,1,1,N'',N'https://img.youtube.com/vi/skMtNVd3h-Y/hqdefault.jpg',0);
